# Generated by Django 3.2.6 on 2021-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('setup', models.CharField(max_length=200, null=True)),
                ('punchline', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
